"""remove totalamount

Revision ID: 19fc70c82c3b
Revises: 552161fb437d
Create Date: 2025-06-19 04:32:56.975943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fc70c82c3b'
down_revision: Union[str, None] = '552161fb437d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_incentives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_amount', sa.Float(), nullable=True),
    sa.Column('week_amount', sa.Float(), nullable=True),
    sa.Column('month_amount', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_incentives_id'), 'leaderboard_incentives', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_incentives_id'), table_name='leaderboard_incentives')
    op.drop_table('leaderboard_incentives')
    # ### end Alembic commands ###
