"""Add type column to Incentive

Revision ID: 34b1f2a011e4
Revises: 8ed6412ed146
Create Date: 2025-06-19 15:32:27.387213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b1f2a011e4'
down_revision: Union[str, None] = '8ed6412ed146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incentives', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incentives', 'type')
    # ### end Alembic commands ###
