"""add source column to incentive

Revision ID: 56d5b6ceec79
Revises: 34b1f2a011e4
Create Date: 2025-06-19 15:35:40.721429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d5b6ceec79'
down_revision: Union[str, None] = '34b1f2a011e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incentives', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incentives', 'source')
    # ### end Alembic commands ###
