"""Initial clean migration

Revision ID: 6dfd882061db
Revises: 
Create Date: 2025-06-16 07:04:08.166133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dfd882061db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_mobile'), 'admins', ['mobile'], unique=True)
    op.create_table('outlets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_outlets_id'), 'outlets', ['id'], unique=False)
    op.create_table('products',
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('verticle', sa.String(), nullable=True),
    sa.Column('trait', sa.String(), nullable=True),
    sa.Column('rsp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_verticle'), 'products', ['verticle'], unique=False)
    op.create_table('salesmen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('outlet', sa.String(), nullable=False),
    sa.Column('verticle', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('wallet_balance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salesmen_id'), 'salesmen', ['id'], unique=False)
    op.create_index(op.f('ix_salesmen_mobile'), 'salesmen', ['mobile'], unique=True)
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_state_id'), 'system_state', ['id'], unique=False)
    op.create_table('trait_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trait', sa.String(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trait_configs_id'), 'trait_configs', ['id'], unique=False)
    op.create_index(op.f('ix_trait_configs_trait'), 'trait_configs', ['trait'], unique=True)
    op.create_table('verticles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verticles_id'), 'verticles', ['id'], unique=False)
    op.create_index(op.f('ix_verticles_name'), 'verticles', ['name'], unique=True)
    op.create_table('actual_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actual_sales_id'), 'actual_sales', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_table('incentives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('trait', sa.String(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incentives_id'), 'incentives', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_number', sa.String(), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('continued', sa.Boolean(), nullable=True),
    sa.Column('day_streak_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaks_date'), 'streaks', ['date'], unique=False)
    op.create_index(op.f('ix_streaks_id'), 'streaks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaks_id'), table_name='streaks')
    op.drop_index(op.f('ix_streaks_date'), table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_incentives_id'), table_name='incentives')
    op.drop_table('incentives')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_actual_sales_id'), table_name='actual_sales')
    op.drop_table('actual_sales')
    op.drop_index(op.f('ix_verticles_name'), table_name='verticles')
    op.drop_index(op.f('ix_verticles_id'), table_name='verticles')
    op.drop_table('verticles')
    op.drop_index(op.f('ix_trait_configs_trait'), table_name='trait_configs')
    op.drop_index(op.f('ix_trait_configs_id'), table_name='trait_configs')
    op.drop_table('trait_configs')
    op.drop_index(op.f('ix_system_state_id'), table_name='system_state')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_salesmen_mobile'), table_name='salesmen')
    op.drop_index(op.f('ix_salesmen_id'), table_name='salesmen')
    op.drop_table('salesmen')
    op.drop_index(op.f('ix_products_verticle'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_outlets_id'), table_name='outlets')
    op.drop_table('outlets')
    op.drop_index(op.f('ix_admins_mobile'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
