"""remove totalamount

Revision ID: 75069e8f689c
Revises: f99f998de433
Create Date: 2025-06-17 16:48:32.764734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75069e8f689c'
down_revision: Union[str, None] = 'f99f998de433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('amount', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
