"""create reward_log table

Revision ID: 8ed6412ed146
Revises: cc2f1d6fb6ed
Create Date: 2025-06-19 15:11:53.776722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed6412ed146'
down_revision: Union[str, None] = 'cc2f1d6fb6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('salesman_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', 'date', name='unique_reward')
    )
    op.create_index(op.f('ix_reward_log_date'), 'reward_log', ['date'], unique=False)
    op.create_index(op.f('ix_reward_log_id'), 'reward_log', ['id'], unique=False)
    op.create_index(op.f('ix_reward_log_period'), 'reward_log', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_log_period'), table_name='reward_log')
    op.drop_index(op.f('ix_reward_log_id'), table_name='reward_log')
    op.drop_index(op.f('ix_reward_log_date'), table_name='reward_log')
    op.drop_table('reward_log')
    # ### end Alembic commands ###
