"""re-add amount column

Revision ID: c6fb3e2653aa
Revises: ff0ba7d89682
Create Date: 2025-06-17 17:11:18.392120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fb3e2653aa'
down_revision: Union[str, None] = 'ff0ba7d89682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'amount')
    # ### end Alembic commands ###
