"""remove totalamount

Revision ID: f99f998de433
Revises: 38452b5af28a
Create Date: 2025-06-17 16:15:01.561457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99f998de433'
down_revision: Union[str, None] = '38452b5af28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('total_amount', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
